# -*- coding: utf-8 -*-
{
    "name": "Professional Report Templates Seedor",
    "license": "OPL-1",
    "support": "support@seedorsoft.com",
    "summary": """
         customized templates""",
    "description": """  """,
    "author": "Poovarasan",
    "website": "http://www.seedorsoft.com",
    "category": "Accounting & Finance",
    "version": "13.0.2.1.0",
    # any module necessary for this one to work correctly
    "depends": [
        "professional_templates",
    ],
    "data": [
        "invoice/seedor1_template.xml",
        "invoice/seedor2_template.xml",
        "invoice/seedor3_template.xml",
        "invoice/seedor4_template.xml",
        "invoice/seedor5_template.xml",
        "invoice/switch_templates.xml",
        "sale_order/seedor1_template.xml",
        "sale_order/seedor2_template.xml",
        "sale_order/switch_templates.xml",
        "sale_order/seedor3_template.xml",
        "sale_order/seedor4_template.xml",
        "sale_order/seedor5_template.xml",
        "purchase_order/switch_templates.xml",
        "purchase_order/seedor1_template.xml",
        "purchase_order/seedor2_template.xml",
        "purchase_order/seedor3_template.xml",
        "purchase_order/seedor4_template.xml",
        "purchase_order/seedor5_template.xml",
        "rfq/seedor1_template.xml",
        "rfq/seedor2_template.xml",
        "rfq/switch_templates.xml",
        "rfq/seedor3_template.xml",
        "rfq/seedor4_template.xml",
        "rfq/seedor5_template.xml",
        "delivery_note/switch_templates.xml",
        "delivery_note/seedor1_template.xml",
        "delivery_note/seedor2_template.xml",
        "delivery_note/seedor3_template.xml",
        "delivery_note/seedor4_template.xml",
        "delivery_note/seedor5_template.xml",
        "picking/switch_templates.xml",
        "picking/seedor1_template.xml",
        "picking/seedor2_template.xml",
        "picking/seedor3_template.xml",
        "picking/seedor4_template.xml",
        "picking/seedor5_template.xml",
    ],
    # only loaded in demonstration mode
    "demo": [
        # 'demo.xml',
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
}
