# -*- encoding: utf-8 -*-
{
    'name': 'Asterisk Calls CRM',
    'version': '3.8',
    'author': 'Odooist',
    'price': 0,
    'currency': 'EUR',
    'maintainer': 'Odooist',
    'support': 'odooist@gmail.com',
    'license': 'OPL-1',
    'category': 'Phone',
    'summary': 'Asterisk Calls CRM integration',
    'description': "",
    'depends': ['crm', 'asterisk_calls', 'asterisk_common'],
    'data': [
        'views/crm_lead.xml',
        'views/call.xml',
        'views/channel.xml',
        'views/resources.xml',
        'views/settings.xml',
        'security/agent.xml',
    ],
    'demo': [],
    "qweb": ['static/src/xml/*.xml'],
    'installable': True,
    'application': False,
    'auto_install': False,
    'images': ['static/description/history_graph_crm.png'],
}
