{
    'name' : 'Attendance Onboarding',
    'version' : '1.1',
    'summary': '',
    'sequence': 15,
    'description': """======================""",
    'category': 'hr_attendance',
    'website': ' ',
    'images' : ['images/accounts.jpeg','images/bank_statement.jpeg','images/cash_register.jpeg','images/chart_of_accounts.jpeg','images/customer_invoice.jpeg','images/journal_entries.jpeg'],
    'depends' : ['hr_attendance','attendance_regularization','oh_employee_documents_expiry','google_sheet_data_import','oh_hr_zk_attendance'],
    'data': [
       'views/attendance_onboarding.xml',
       'views/attendance_onboarding_template.xml',
       'views/attendance_onboarding_default_template.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    # 'post_init_hook': '_auto_install_l10n',
}