{
    'name': ' Checklist For Maintenance Module',
    'summary': """Checklist For Maintenance""",
    'version': '13.0',
    'description': """ Checklist For Maintenance""",
    'author': 'Fousia Banu A R',
    'company': 'Seedorsoft Pvt Ltd',
    'website': 'https://www.seedorsoft.com',
    'category': 'Tools',
    'depends': ['maintenance','product'],
    'license': 'AGPL-3',
    'data': [
        'view.xml',
        'security.xml',
        #'ir.model.access.csv',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
}