{
    "name": """stock balance report""",
    "summary": """Stock Balance Report Wizard""",
    "category": "Extra Tools",
    # "live_test_url": "http://apps.it-projects.info/shop/product/DEMO-URL?version=13.0",
    "images": [],
    "version": "13.0.1.0.0",
    "application": False,
    "author": "Jnz",
    "support": "",
    "website": "",
    "license": "Other OSI approved licence",  # MIT
    # "price": 9.00,
    # "currency": "EUR",
    "depends": ["web", 'product'],
    "external_dependencies": {"python": [], "bin": []},
    "data": ['views/views.xml'],
    "demo": [],
    "qweb": [],
    "post_load": None,
    "pre_init_hook": None,
    'post_init_hook': None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}