{
    'name'         : "Calendar Extend",
    'author'       : 'Fousia banu A.R',
    'category'     : 'API',
    'summary'      : """Calendar Extend""",
    'website'      : '',
    'company'      : '',
    'maintainer'   : '',
    'description'  : """This Module extends calender.""",
    'version'      : '1.0',
    'depends'      : ['base', 'calendar'],
    'data'         : [],
    "images"       : [],
    "qweb"         :  [],
    'license'      : 'LGPL-3',
    'installable'  : True,
    'application'  : True,
    'auto_install' : False,
}
