{
    "name": """star""",
    "summary": """This module allows blocking backend access when database limit is exceeded""",
    "category": "Extra Tools",
    # "live_test_url": "http://apps.it-projects.info/shop/product/DEMO-URL?version=13.0",
    "images": [],
    "version": "13.0.1.0.0",
    "application": False,
    "author": "IT-Projects LLC, Eugene Molotov",
    "support": "apps@it-projects.info",
    "website": "https://apps.odoo.com/apps/modules/13.0/database_limit_size/",
    "license": "Other OSI approved licence",  # MIT
    # "price": 9.00,
    # "currency": "EUR",
    "depends": ["web"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ['views/views.xml'],
    "demo": [],
    "qweb": [],
    "post_load": None,
    "pre_init_hook": None,
    'post_init_hook': None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}