# -*- encoding: utf-8 -*-
{
    'name': 'Asterisk Calls',
    'version': '3.8',
    'author': 'Odooist',
    'price': 350.0,
    'currency': 'EUR',
    'maintainer': 'Odooist',
    'support': 'odooist@gmail.com',
    'license': 'OPL-1',
    'category': 'Phone',
    'summary': 'VoIP call tracking and management',
    'description': 'Asterisk based VoIP application.',
    'depends': ['asterisk_common', 'mail', 'board'],
    'data': [
        'security/agent/ir.model.access.csv',
        'security/agent/security.xml',
        'security/user/security.xml',
        'security/user/ir.model.access.csv',
        'security/admin/security.xml',
        'security/admin/ir.model.access.csv',
        'security/supervisor/supervisor_access_rules.xml',
        'security/supervisor/supervisor_record_rules.xml',
        'views/views.xml',
        'views/resources.xml',
        'views/call.xml',
        'views/library.xml',
        'views/tag.xml',
        'views/user.xml',
        'views/channel.xml',
        'views/res_partner.xml',
        'views/settings.xml',
        'views/ir_cron.xml',
        'views/templates.xml',
        # statistics
        'reports/incoming.xml',
        'reports/outgoing.xml',
        # Reports
        'reports/reports.xml',
        'reports/calls_report.xml',
        # Wizards
        'wizard/call.xml',
        # Data
        'data/channel.xml',
        'data/calls_events.xml',
        'data/res_partner.xml',
    ],
    'demo': [],
    "qweb": ['static/src/xml/*.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': ['static/description/logo1.png'],
}
