from . import call
from . import event
from . import tag
from . import channel
from . import user
from . import res_partner
from . import res_users
from . import settings
from . import callback
from . import user
