# -*- coding: utf-8 -*-
{
    'name': 'Held Products',
    'version': '13.0.1.5',
    'category': 'Proof of Concept',
    'summary': 'Studio App: Manage Customer specific purchases, with alerts and traceability',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'Odoo Technical Marketing',
    'depends': [
        'base',
        'stock',
        'sale_management',
        'web_studio',
    ],
    'data': [
        'data/ir_model_fields.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
    ],
    'application': False,
    'license': 'OPL-1',
    'support': 'Unsupported',
    'images': [
        'images/main_screenshot.png'
    ],
}
