language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.6"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility
      - postgis postgresql-9.6-postgis-2.3 # travis doesn't know which one to install
      - postgresql-9.6-postgis-2.3-scripts # pre-installed on travis but required for runbot

stages:
  - test

jobs:
  include:
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT="1"
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="OCA/OCB"
env:
  global:
    - VERSION="13.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
    - MQT_DEP=PIP

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install geojson Shapely sphinx sphinx_bootstrap_theme sphinx-intl
    odoo-sphinx-autodoc

before_script:
  - if [ "$TESTS" -e "1" ] ; then psql -U postgres -d postgres -c "create extension
    postgis"; fi
  - if [ "$TESTS" -e "1" ] ; then psql -U postgres -d postgres -c "create extension
    postgis_topology"; fi

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
